name: Guard dev PRs
on:
  pull_request:
    branches: [ "dev" ]
permissions:
  contents: read
  pull-requests: read
jobs:
  signed-commits:
    name: require-verified-commits
    runs-on: ubuntu-latest
    steps:
      - name: Check all commits in PR are verified
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          sudo apt-get update -y >/dev/null 2>&1 || true
          sudo apt-get install -y jq >/dev/null 2>&1 || true
          commits_json=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/commits)
          if echo "$commits_json" | jq 'map(.commit.verification.verified) | all' | grep -q true; then
            echo "All commits in this PR are Verified ✅"
          else
            echo "❌ This PR contains unsigned/unverified commits. Please rebase/sign them." >&2
            exit 1
          fi
