name: Project: PR merged on main -> Done
on:
  pull_request:
    types: [closed]

jobs:
  set-done:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      OWNER: jaygtel
      PROJECT_TITLE: Jays Website
      CONTENT_ID: ${{ github.event.pull_request.node_id }}
      GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
    steps:
      - name: Resolve project number by title
        run: |
          PN=$(gh project list --owner "$OWNER" --format json --jq '.[] | select(.title==env.PROJECT_TITLE) | .number')
          [ -z "$PN" ] && { echo "Project not found"; exit 1; }
          echo "PROJECT_NUMBER=$PN" >> $GITHUB_ENV

      - name: Fetch project + Status/Done IDs
        run: |
          gh api graphql -f query='
            query($login:String!, $number:Int!){
              user(login:$login){
                projectV2(number:$number){
                  id
                  fields(first:50){
                    nodes{
                      ... on ProjectV2SingleSelectField {
                        id name
                        options { id name }
                      }
                    }
                  }
                }
              }
            }' -f login="$OWNER" -F number="$PROJECT_NUMBER" > project.json
          echo "PROJECT_ID=$(jq -r .data.user.projectV2.id project.json)" >> $GITHUB_ENV
          echo "STATUS_FIELD_ID=$(jq -r ".data.user.projectV2.fields.nodes[] | select(.name==\"Status\") | .id" project.json)" >> $GITHUB_ENV
          echo "DONE_OPT_ID=$(jq -r ".data.user.projectV2.fields.nodes[] | select(.name==\"Status\") | .options[] | select(.name==\"Done\") | .id" project.json)" >> $GITHUB_ENV

      - name: Ensure PR exists in the project (capture item id if newly added)
        run: |
          NEW_ID=$(gh api graphql -f query='
            mutation($project:ID!, $content:ID!){
              addProjectV2ItemById(input:{projectId:$project, contentId:$content}) { item { id } }
            }' -f project="$PROJECT_ID" -f content="$CONTENT_ID" --jq '.data.addProjectV2ItemById.item.id' || true)
          [ -n "$NEW_ID" ] && echo "ITEM_ID=$NEW_ID" >> $GITHUB_ENV

      - name: Find project item id if not new
        if: env.ITEM_ID == ''
        run: |
          gh api graphql -f query='
            query($login:String!, $number:Int!){
              user(login:$login){
                projectV2(number:$number){
                  items(first:200){
                    nodes{ id content { ... on PullRequest { id } } }
                  }
                }
              }
            }' -f login="$OWNER" -F number="$PROJECT_NUMBER" \
            --jq ".data.user.projectV2.items.nodes[] | select(.content.id==\"$CONTENT_ID\") | .id" > item_id.txt
          echo "ITEM_ID=$(cat item_id.txt)" >> $GITHUB_ENV

      - name: Set Status = Done
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $item:ID!, $field:ID!, $opt:String!){
              updateProjectV2ItemFieldValue(
                input:{projectId:$project, itemId:$item, fieldId:$field, value:{singleSelectOptionId:$opt}}
              ){ projectV2Item { id } }
            }' -f project="$PROJECT_ID" -f item="$ITEM_ID" -f field="$STATUS_FIELD_ID" -f opt="$DONE_OPT_ID"
