name: Enforce merges from dev only

on:
  pull_request:
    branches: [ main ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from dev
        run: |
          echo "Head ref: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Only 'dev' can be merged into 'main'."
            exit 1
          fi
